/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class posix_SharedMem */

#ifndef _Included_posix_SharedMem
#define _Included_posix_SharedMem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     posix_SharedMem
 * Method:    getLBA
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_posix_SharedMem_getLBA
  (JNIEnv *, jclass);

/*
 * Class:     posix_SharedMem
 * Method:    shmctl
 * Signature: (IILposix/SharedMem$shmid_ds;)I
 */
JNIEXPORT jint JNICALL Java_posix_SharedMem_shmctl
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     posix_SharedMem
 * Method:    shmat
 * Signature: (IJI)J
 */
JNIEXPORT jlong JNICALL Java_posix_SharedMem_shmat
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     posix_SharedMem
 * Method:    shmdt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_posix_SharedMem_shmdt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     posix_SharedMem
 * Method:    shmget
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_posix_SharedMem_shmget
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
