/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class posix_CPtr */

#ifndef _Included_posix_CPtr
#define _Included_posix_CPtr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     posix_CPtr
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_posix_CPtr_init
  (JNIEnv *, jclass);

/*
 * Class:     posix_CPtr
 * Method:    alignOf
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_posix_CPtr_alignOf
  (JNIEnv *, jclass, jint);

/*
 * Class:     posix_CPtr
 * Method:    sizeOf
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_posix_CPtr_sizeOf
  (JNIEnv *, jclass, jint);

/*
 * Class:     posix_CPtr
 * Method:    copyOut
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_posix_CPtr_copyOut
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     posix_CPtr
 * Method:    copyIn
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_posix_CPtr_copyIn
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     posix_CPtr
 * Method:    getByte
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_posix_CPtr_getByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     posix_CPtr
 * Method:    setByte
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_posix_CPtr_setByte
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     posix_CPtr
 * Method:    getShort
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_posix_CPtr_getShort
  (JNIEnv *, jobject, jint);

/*
 * Class:     posix_CPtr
 * Method:    setShort
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_posix_CPtr_setShort
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     posix_CPtr
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_posix_CPtr_getInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     posix_CPtr
 * Method:    setInt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_posix_CPtr_setInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     posix_CPtr
 * Method:    getCShort
 * Signature: (II)S
 */
JNIEXPORT jshort JNICALL Java_posix_CPtr_getCShort
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     posix_CPtr
 * Method:    setCShort
 * Signature: (IIS)V
 */
JNIEXPORT void JNICALL Java_posix_CPtr_setCShort
  (JNIEnv *, jobject, jint, jint, jshort);

/*
 * Class:     posix_CPtr
 * Method:    getCInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_posix_CPtr_getCInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     posix_CPtr
 * Method:    setCInt
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_posix_CPtr_setCInt
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
