/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class posix_IPC */

#ifndef _Included_posix_IPC
#define _Included_posix_IPC
#ifdef __cplusplus
extern "C" {
#endif
#undef posix_IPC_IPC_RMID
#define posix_IPC_IPC_RMID 0L
#undef posix_IPC_IPC_SET
#define posix_IPC_IPC_SET 1L
#undef posix_IPC_IPC_STAT
#define posix_IPC_IPC_STAT 2L
#undef posix_IPC_IPC_PRIVATE
#define posix_IPC_IPC_PRIVATE 0L
#undef posix_IPC_IPC_ALLOC
#define posix_IPC_IPC_ALLOC 32768L
#undef posix_IPC_IPC_CREAT
#define posix_IPC_IPC_CREAT 512L
#undef posix_IPC_IPC_EXCL
#define posix_IPC_IPC_EXCL 1024L
#undef posix_IPC_IPC_NOWAIT
#define posix_IPC_IPC_NOWAIT 2048L
#undef posix_IPC_IPC_CI
#define posix_IPC_IPC_CI 4096L
#undef posix_IPC_IPC_NOCLEAR
#define posix_IPC_IPC_NOCLEAR 8192L
#undef posix_IPC_IPC_PHYS
#define posix_IPC_IPC_PHYS 16384L
/*
 * Class:     posix_IPC
 * Method:    ftok
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_posix_IPC_ftok
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     posix_IPC
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_posix_IPC_init
  (JNIEnv *, jclass);

/*
 * Class:     posix_IPC
 * Method:    geteuid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_posix_IPC_geteuid
  (JNIEnv *, jclass);

/*
 * Class:     posix_IPC
 * Method:    getegid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_posix_IPC_getegid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
