/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class posix_Malloc */

#ifndef _Included_posix_Malloc
#define _Included_posix_Malloc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     posix_Malloc
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_posix_Malloc_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     posix_Malloc
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_posix_Malloc_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
