/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class posix_Signal */

#ifndef _Included_posix_Signal
#define _Included_posix_Signal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     posix_Signal
 * Method:    sigwait
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_posix_Signal_sigwait
  (JNIEnv *, jclass);

/*
 * Class:     posix_Signal
 * Method:    sigmap
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_posix_Signal_sigmap
  (JNIEnv *, jclass, jint);

/*
 * Class:     posix_Signal
 * Method:    kill
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_posix_Signal_kill
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     posix_Signal
 * Method:    sigaction
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_posix_Signal_sigaction
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
