/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class posix_SemSet */

#ifndef _Included_posix_SemSet
#define _Included_posix_SemSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     posix_SemSet
 * Method:    semget
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_posix_SemSet_semget
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     posix_SemSet
 * Method:    semctl
 * Signature: (IIILposix/SemSet$semid_ds;)I
 */
JNIEXPORT jint JNICALL Java_posix_SemSet_semctl__IIILposix_SemSet_00024semid_1ds_2
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     posix_SemSet
 * Method:    semctl
 * Signature: (III[S)I
 */
JNIEXPORT jint JNICALL Java_posix_SemSet_semctl__III_3S
  (JNIEnv *, jclass, jint, jint, jint, jshortArray);

/*
 * Class:     posix_SemSet
 * Method:    semctl
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_posix_SemSet_semctl__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     posix_SemSet
 * Method:    semop
 * Signature: (I[S)I
 */
JNIEXPORT jint JNICALL Java_posix_SemSet_semop
  (JNIEnv *, jclass, jint, jshortArray);

/*
 * Class:     posix_SemSet
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_posix_SemSet_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
