/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class posix_Stat */

#ifndef _Included_posix_Stat
#define _Included_posix_Stat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     posix_Stat
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_posix_Stat_init
  (JNIEnv *, jclass);

/*
 * Class:     posix_Stat
 * Method:    stat
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_posix_Stat_stat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     posix_Stat
 * Method:    umask
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_posix_Stat_umask__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     posix_Stat
 * Method:    umask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_posix_Stat_umask__
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
